#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*)
    npx.cmd lint-staged
    npx.cmd pretty-quick --staged
  ;;
  *)
    npx lint-staged
    npx pretty-quick --staged
  ;;
esac


